version: "3.5"

services:
  mysql:
    build: ./scripts/Docker/bin/mysql
    container_name: 'rest-api-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD